### ISSUE TITLE
Change the stroke width

### ISSUE THREAD

**Issue by zainuwachtig** [Foohx/tabler-icons-to-expo#1]
Is it is a possibility to add an option to change the stroke width (or is there a way to do it on my own)?

**Comment by Foohx** [comment]
Hi !

Unfortunately, no, this is not currently possible. We use a TTF font format here, so the weights are not changeable. Additionally, the text-stroke* properties are not available in React Native.

You can attempt to modify the TTF file to create a version with thicker/thiness lines.

You can also play with shadows, but this remains very limited: 
```tsx
        <TablerIcon
          name="heart"
          size={50}
          color="black"
          style={{
            textShadowColor: "red",
            textShadowOffset: { width: 0, height: 0 },
            textShadowRadius: 8,
          }}
        />
```

However, if you truly need to achieve this, the simplest approach is to work with icons in SVG format.
