### ISSUE TITLE
Typescript Error for Name

### ISSUE THREAD

**Issue by tyeetale** [Foohx/tabler-icons-to-expo#2]
I followed the thread on adding tabler from expo vector icons, and the documentation outlined here, but I have found there is a type error on my side that is as follows:
```
Type '"heart"' is not assignable to type '"tabler-icons"'.ts(2322)

createIconSet.d.ts(17, 5): The expected type comes from property 'name' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<IconProps<"tabler-icons">, {}, any>> & Pick<...> & InexactPartial<...> & InexactPartial<...>'
```

Perhaps I did something wrong, but would like to know how to fix this!

**Comment by Foohx** [comment]
Hi @tyeetale ,

Can you provide a repository or code to reproduce your issue?

Thanks

**Comment by Foohx** [comment]
I recommend using the react native version: https://tabler.io/docs/icons/react-native
